#
# IMPORTANT NOTE
#
# This chart inherits from the k8s@Home common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/master/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: openhab/openhab
  # -- image tag
  tag: 3.2.0-alpine
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

  # -- Set the correct user id
  USER_ID: 9001
  # -- Set the correct group id
  GROUP_ID: 9001

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false


# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  conf:
    enabled: false
    mountPath: /openhab/conf

  userdata:
    enabled: false
    mountPath: /openhab/userdata

  addons:
    enabled: false
    mountPath: /openhab/addons

  java:
    enabled: false
    mountPath: /openhab/.java


# -- Configures the probes for the main Pod.
# @default -- See values.yaml
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
